/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: RELbotSimple
 *  expmt: RELbotSimple
 *  date:  March 27, 2026
 *  time:  2:28:57 PM
 *  user:  University of Twente
 *  from:  -
 *  build: 5.1.6.14106
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
